apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: dev-tenant
  namespace: 3scale-dev
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: admin
  systemMasterUrl: https://master.apps.cluster-xrjzh.xrjzh.sandbox2942.opentlc.com
  email: admin@ecorp.com
  organizationName: dev
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale
  passwordCredentialsRef:
    name: dev-admin-secret
  tenantSecretRef:
    name: dev-tenant-secret
  #  namespace: 3scale-dev
    