apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: 3scale-qa
  namespace: 3scale-qa
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    insecure_skip_verify: true
spec:
  username: admin
  systemMasterUrl: https://master.$(DOMAIN)
  email: admin@ecorp.com
  organizationName: 3scale-qa
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale
  passwordCredentialsRef:
    name: qa-admin-secret
  tenantSecretRef:
    name: qa-tenant-secret
    