apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# bases:
#  - ../../base-operator

# generatorOptions:
#  disableNameSuffixHash: true
# secretGenerator:
# - name: keycloak-db-secret
#   envs:
#   - env/bd-credential.env
# - name: credential-keycloak
#   envs:
#   - env/sso-credential.env

# patches:
# - patch: |-
#     - op: add
#       path: /spec/targetNamespaces/-
#       value: 3scale-dev
#   target:
#     group: operators.coreos.com
#     kind: OperatorGroup
#     name: 3scale
#     version: v1


resources: 
#- namespace.yaml
- tenant.yaml
- dev-admin-secret.yaml
- dev-user-secret.yaml

- rolebinding.yaml
#- product/product-01.yaml
#- product/product-511.yaml


- product/echo-product.yaml
- product/echo-backend.yaml
##- product/account.yaml
- product/accountuser.yaml
- product/app-echoapi.yaml
#- product/user.yaml
# - sso-realms/test-client-testclient.yaml
# - sso-realms/test-realm.yaml
