---
kind: DeveloperAccount
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: clhqa
spec:
  orgName: clh
  providerAccountRef:
    name: dev-tenant-secret
    namespace: 3scale
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: qauserclh
spec:
  developerAccountRef:
    name: clhqa
  email: clhqa@example.com
  passwordCredentialsRef:
    name: dev-user-secret
  role: admin
  username: qauserclh
  providerAccountRef:
    name: dev-tenant-secret
    namespace: 3scale