---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    operators.coreos.com/apicast-operator.3scale-borrar: ''
  name: apicast-operator
spec:
  channel: threescale-2.14
  installPlanApproval: Automatic
  name: apicast-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: apicast-operator.v0.8.0

