apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-sample
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  wildcardDomain: apps.cluster-v2pdq.v2pdq.sandbox2054.opentlc.com
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: s3-auth
