apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
 - ../../base-operator

# generatorOptions:
#  disableNameSuffixHash: true
# secretGenerator:
# - name: keycloak-db-secret
#   envs:
#   - env/bd-credential.env
# - name: credential-keycloak
#   envs:
#   - env/sso-credential.env

patches:
- patch: |-
    - op: add
      path: /spec/targetNamespaces/-
      value: 3scale
  target:
    group: operators.coreos.com
    kind: OperatorGroup
    name: 3scale
    version: v1


resources: 
#- namespace.yaml
- 3scale-instance.yaml
- secret-s3-auth.yaml
- clusterrole.yaml
