apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base-operator-apicast

# configurations:
#   - config.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: token-apicast-staging
  envs:
  - env/token-secret.env
- name: token-apicast-production
  envs:
  - env/token-secret.env

patches:
- patch: |-
    - op: add
      path: /spec/targetNamespaces/-
      value: 3scale-apicast-qa
  target:
    group: operators.coreos.com
    kind: OperatorGroup
    name: 3scale-apicast
    version: v1

# replacements:
#   - path: image-tag-replacement.yaml

resources: 
#- namespace.yaml
- resources/apicast-instance-staging.yaml
- resources/apicast-instance-production.yaml




vars:
  - name: DOMAIN
    objref:
      apiVersion: apps.3scale.net/v1alpha1
      kind: APIManager
      name: apimanager
    fieldref:
      fieldpath: spec.wildcardDomain

